spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/hunters_league
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

  docker:
    compose:
      enabled: true
      lifecycle-management: start_only
      file: src/main/docker/compose.yaml

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        default_schema: public
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect



  liquibase:
    enabled: true
    change-log: db/changelog/master.yaml


server:
  port: 8443
  ssl:
    enabled: true
    key-alias: spring-https
    key-store: classpath:java.p12
    key-store-password: password
    key-store-type: PKCS12
    key-password: password