spring:
#
#  datasource:
#    username: GreenPulse
#    password:
#    url: jdbc:postgresql://localhost:5432
#    driver-class-name: org.postgresql.Driver

  docker:
    compose:
      enabled: true
      lifecycle-management: start_only
      file: src/main/docker/compose.yaml

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        default_schema: public
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: true
    change-log: db/changelog/master.yaml

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration,org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
