version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: unless-stopped
    user: root
    networks:
        - sonarqube-network
    ports:
      - "8082:8080"
      - "50000:50000" # Pour la communication avec les agents Jenkins
    volumes:
      - C:\Users\Youcode\jinkis_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock # Partager le socket Docker de l'hôte

networks:
  sonarqube-network :
    external: true